### PR TITLE
Upgrade org.json:json to 20230227

### PR DESCRIPTION
**Pull request by damienbailly**
Solves https://github.com/snyk/gradle-plugin/issues/23

### CODE REVIEW

**Review by swerfel — APPROVED** [review]
👍

**Comment by abhilashmandaliya** [comment]
@swerfel any idea when will this be merged and released?

**Comment by rikcdpg** [comment]
@bmvermeer are you in power to merge and release this?

**Comment by rikcdpg** [comment]
@dotkas thanks, any idea when a new version will be released?

**Comment by dotkas** [comment]
@rikcdpg follow along https://github.com/snyk/cli/pull/4705 😃

**Comment by dotkas** [comment]
@rikcdpg Wow, this is taking longer than expected, apologies for that. I hope to have it in soon.

**Pull request merged**
