### PR TITLE
Fix org.json:json high security vulnerability

### PR DESCRIPTION
**Pull request by CedricFinance**
https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-5962464

### CODE REVIEW

**Comment by oualidsr** [comment]
➕

**Comment by oualidsr** [comment]
Seems fixed later in https://github.com/snyk/gradle-plugin/pull/31/files

**Review by usmonster — APPROVED** [review]

**Comment by steven-sheehy** [comment]
It's quite ironic that I'm getting a Snyk vulnerability report that fails my CI pipeline and it turns out that the actual vulnerability is in Snyk itself (technically its plugin) and has no fixed version. It seems like this was partially fixed in https://github.com/snyk/gradle-plugin/pull/31 but the fix was incomplete. Anyway to get this prioritized and released?

**Comment by steven-sheehy** [comment]
I was able to workaround the vulnerability with the below:

```gradle
configurations["dataFiles"].dependencies.add(dependencies.create("org.json:json:20231013"))
```

**Comment by bmvermeer** [comment]
this is resolved in latest version

**Pull request closed without merging**
